config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

	namespace :api, :defaults => {:format => :json} do
		resources :races do
			resources :runners do
				get 'datatable', on: :collection
			end
		end
	end
  
  resources :races do
	  resources :runners
	end

  root 'races#index'

end

app/models/runner.rb
class Runner < ActiveRecord::Base
	
  self.primary_key = 'place'
  
  belongs_to :race
  
  before_validation :convert_durations_to_integers
  
  def convert_durations_to_integers
    self.gun_time = ChronicDuration::parse(self.gun_time_before_type_cast) if attribute_present?("gun_time")
    self.gun_pace = ChronicDuration::parse(self.gun_pace_before_type_cast) if attribute_present?("gun_pace")
    self.net_time = ChronicDuration::parse(self.net_time_before_type_cast) if attribute_present?("net_time")
    self.net_pace = ChronicDuration::parse(self.net_pace_before_type_cast) if attribute_present?("net_pace")
  end

  def gun_time
    ChronicDuration.output(read_attribute(:gun_time), :format => :chrono)
  end

  def gun_pace
    ChronicDuration.output(read_attribute(:gun_pace), :format => :chrono)
  end

  def net_time
    ChronicDuration.output(read_attribute(:net_time), :format => :chrono)
  end

  def net_pace
    ChronicDuration.output(read_attribute(:net_pace), :format => :chrono)
  end	
end

app/controllers/api/runners_controller.rb
class API::RunnersController < ApplicationController
  before_action :set_race, only: [:index, :show, :datatable]
  before_action :set_runner, only: [:show]

  # GET /runners
  # GET /runners.json
  def index
    @runners = Race.find(params[:race_id]).runners
  end
  
  # GET /runners/datatable
  # GET /runners/datatable.json
  def datatable
  	
    per_page = params[:length].to_i > 0 ? params[:length].to_i : 10
    page = params[:start].to_i/per_page + 1
    order_column = %w[place name sex group time pace location][params[:order]['0'][:column].to_i]
    order_direction = params[:order]['0'][:dir] || "ASC"
    order = order_column + " " + order_direction
  
    query = {}
    query.merge!({ :name_cont => params[:search][:value] }) if !params[:search][:value].blank?
    @q = @race.runners.search(query)
    runners = @q.result.order(order)
    runners_paged = runners.page(page).per_page(per_page)
        
    datatable = {
      draw: params[:draw].to_i,
      recordsTotal: @race.runners.length,
      recordsFiltered: runners.length,
      data: runners_paged.map{ |r|
        {
          place: r.place,
          name: r.name,
          sex: r.sex,
          group: r.age_group,
          time: r.net_time,
          pace: r.net_pace,
          location: [ r.city, r.state, r.country ].reject(&:blank?).join(', '),
          link: race_runner_path(@race,r)
        }
      }
    }
    
    respond_to do |format|
      format.json { render json: datatable }
    end

  end

  # GET /runners/1
  # GET /runners/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:race_id])
    end

    def set_runner
      @runner = Runner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
      params.require(:runner).permit(:name, :place, :sex, :place_in_sex, :place_in_age_group, :age_group, :gun_time, :gun_pace, :net_time, :net_pace, :country, :state, :city)
    end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_race, only: [:index, :show]
  before_action :set_runner, only: [:show]

  # GET /runners
  # GET /runners.json
  def index
    query = {}
    query.merge!(params[:q]) if !params[:q].blank?
    @q = @race.runners.search(query)
    @runners = @q.result.order('place ASC').page(params[:page]).per_page(10)
  end

  # GET /runners/1
  # GET /runners/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:race_id])
    end

    def set_runner
      @runner = Runner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
      params.require(:runner).permit(:name, :place, :sex, :place_in_sex, :place_in_age_group, :age_group, :gun_time, :gun_pace, :net_time, :net_pace, :country, :state)
    end
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_form.html.erb
<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.number_field :place %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :place_in_sex %><br>
    <%= f.number_field :place_in_sex %>
  </div>
  <div class="field">
    <%= f.label :place_in_age_group %><br>
    <%= f.number_field :place_in_age_group %>
  </div>
  <div class="field">
    <%= f.label :age_group %><br>
    <%= f.text_field :age_group %>
  </div>
  <div class="field">
    <%= f.label :gun_time %><br>
    <%= f.time_select :gun_time %>
  </div>
  <div class="field">
    <%= f.label :gun_pace %><br>
    <%= f.time_select :gun_pace %>
  </div>
  <div class="field">
    <%= f.label :net_time %><br>
    <%= f.time_select :net_time %>
  </div>
  <div class="field">
    <%= f.label :net_pace %><br>
    <%= f.time_select :net_pace %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runners/edit.html.erb
<h1>Editing runner</h1>

<%= render 'form' %>

<%= link_to 'Show', @runner %> |
<%= link_to 'Back', runners_path %>

app/views/runners/index.html.erb
<h1>Runners</h1>

<%= search_form_for @q, :url => race_runners_path(@race) do |f| %>
  <fieldset>
    <%= f.label :name_cont %>
    <%= f.text_field :name_cont %>
    <%= f.submit %>
  </fieldset>
<% end %>

<%= will_paginate @runners %>

<table class="table race_runners" data-source="<%= datatable_api_race_runners_path(@race, :format => 'json') %>">
  <thead>
    <tr>
      <th class="number">Place</th>
      <th>Name</th>
      <th class="center">Sex</th>
      <th class="center">Age group</th>
      <th class="number">Time</th>
      <th class="number">Pace</th>
      <th>Location</th>
    </tr>
  </thead>
  <tbody>
    <% @runners.each do |runner| %>
      <tr>
        <td class="number"><%= runner.place %></td>
        <td><%= link_to runner.name, race_runner_path(@race,runner) %></td>
        <td class="center"><%= runner.sex %></td>
        <td class="center"><%= runner.age_group %></td>
        <td class="number"><%= runner.net_time %></td>
        <td class="number"><%= runner.net_pace %></td>
        <td><%= [ runner.city, runner.state, runner.country ].reject(&:blank?).join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @runners %>

app/views/runners/new.html.erb
<h1>New runner</h1>

<%= render 'form' %>

<%= link_to 'Back', runners_path %>

app/views/runners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @runner.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @runner.place %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @runner.sex %>
</p>

<p>
  <strong>Place in sex:</strong>
  <%= @runner.place_in_sex %>
</p>

<p>
  <strong>Place in age group:</strong>
  <%= @runner.place_in_age_group %>
</p>

<p>
  <strong>Age group:</strong>
  <%= @runner.age_group %>
</p>

<p>
  <strong>Gun time:</strong>
  <%= @runner.gun_time %>
</p>

<p>
  <strong>Gun pace:</strong>
  <%= @runner.gun_pace %>
</p>

<p>
  <strong>Net time:</strong>
  <%= @runner.net_time %>
</p>

<p>
  <strong>Net pace:</strong>
  <%= @runner.net_pace %>
</p>

<p>
  <strong>Country:</strong>
  <%= @runner.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @runner.state %>
</p>

<%= link_to 'Back', race_runners_path %>